---
- name: check index.php
  stat:
    path: "{{ nextcloud_webroot }}/index.php"
  register: index
  tags:
    - nextcloud
    - check-install
    - index
    - index.php

- name: check config.php
  stat:
    path: "{{ nextcloud_webroot }}/config/config.php"
  register: config
  tags:
    - nextcloud
    - check-install
    - config
    - config.php
