---
- name: check index.php
  ansible.builtin.stat:
    path: "{{ nextcloud_webroot }}/index.php"
  register: index
  tags:
    - nextcloud
    - check-install
    - index
    - index.php

- name: check config.php
  ansible.builtin.stat:
    path: "{{ nextcloud_webroot }}/config/config.php"
  register: config
  tags:
    - nextcloud
    - check-install
    - config
    - config.php

- name: set_fact
  ansible.builtin.set_fact:
    nextcloud_installed: true
  when: index.stat.exists or config.stat.exists
