---
- name: instance specific config.php
  template:
    src: instance.config.php.j2
    dest: "{{ nextcloud_webroot }}/config/{{ nextcloud_instance }}.config.php"
    owner: www-data
    group: www-data
    mode: "0644"
  tags:
    - nextcloud
    - config

- name: filesystem check changes
  lineinfile:
    path: "{{ nextcloud_webroot }}/config/{{ nextcloud_instance }}.config.php"
    regexp: 'filesystem_check_changes'
    line: "  'filesystem_check_changes' => {{ nextcloud_fs_check_changes }},"
    insertbefore: '^\);$'
    backup: true
  when:
    - nextcloud_fs_check_changes is defined
    - nextcloud_fs_check_changes in [ 0, 1 ]
  tags:
    - nextcloud
    - config

- name: trashbin retention obligation
  lineinfile:
    path: "{{ nextcloud_webroot }}/config/{{ nextcloud_instance }}.config.php"
    regexp: 'trashbin_retention_obligation'
    line:
      "  'trashbin_retention_obligation' =>
      '{{ nextcloud_trashbin_retention_obligation }}',"
    insertbefore: '^\);$'
    backup: true
  when:
    - nextcloud_trashbin_retention_obligation is defined
  tags:
    - nextcloud
    - config

- name: default phone region
  lineinfile:
    path: "{{ nextcloud_webroot }}/config/{{ nextcloud_instance }}.config.php"
    regexp: 'default_phone_region'
    line: "  'default_phone_region' => '{{ nextcloud_default_phone_region }}',"
    insertbefore: '^\);$'
    backup: true
  when:
    - nextcloud_default_phone_region is defined
  tags:
    - nextcloud
    - config
