---
- name: php-cli apc settings
  template:
    src: "php-cli-conf.ini.j2"
    dest: "/etc/php/{{ php_version | default('7.3') }}/cli/conf.d/30-{{ nextcloud_instance }}.ini"
  tags:
    - nextcloud
    - php
    - apc

- name: cron
  cron:
    name: "{{ nextcloud_instance }}"
    minute: "*/{{ nextcloud_cron_frequency_min | default ('5') }}"
    job: "php -f {{ nextcloud_webroot }}/cron.php"
    user: "{{ nextcloud_user }}"
  tags:
    - nextcloud
    - cron
