---
- name: dependencies
  package:
    name: "{{ nextcloud_dependencies }}"
  notify: php-fpm restart
  tags:
    - nextcloud
    - deps
    - dependencies
    - packages

- name: service_facts
  ansible.builtin.service_facts:
  tags:
    - nextcloud
    - facts
