---
- name: Temp folder
  ansible.builtin.tempfile:
    state: directory
    prefix: "{{ role_name }}"
  register: extract_folder
  tags:
    - nextcloud
    - install
    - tempfolder

- name: Unarchive in temp folder
  ansible.builtin.unarchive:
    remote_src: true
    src:
      "https://download.nextcloud.com/server/releases/{{ nextcloud_archive |
      default('latest.tar.bz2') }}"
    dest: "{{ extract_folder.path }}"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
  register: unarchive
  when:
    - extract_folder is succeeded
    - extract_folder.path is defined
  tags:
    - nextcloud
    - install
    - download
    - unarchive

- name: Copy folder to destination
  ansible.builtin.copy:
    remote_src: true
    src: "{{ extract_folder.path }}/nextcloud/"
    dest: "{{ nextcloud_webroot }}"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 0755
  register: copy
  when:
    - unarchive is succeeded
    - extract_folder is succeeded
    - extract_folder.path is defined
  tags:
    - nextcloud
    - install
    - copy

- name: Delete temp folder
  ansible.builtin.file:
    path: "{{ extract_folder.path }}"
    state: absent
  when:
    - copy is succeeded
    - extract_folder is succeeded
    - extract_folder.path is defined
  tags:
    - nextcloud
    - install
    - tempfolder
