---
- name: temp folder
  tempfile:
    state: directory
    prefix: "{{ role_name }}"
  register: extract_folder
  when:
    - not ansible_check_mode
    - not index.stat.exists
  tags:
    - nextcloud
    - install
    - tempfile

- name: unarchive in temp folder
  unarchive:
    remote_src: true
    src:
      "https://download.nextcloud.com/server/releases/{{ nextcloud_version |
      default ('latest.tar.bz2') }}"
    dest: "{{ extract_folder.path }}"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
  register: unarchive
  when:
    - not ansible_check_mode
    - webroot.stat.exists
    - not index.stat.exists
  tags:
    - nextcloud
    - install
    - download
    - unarchive

- name: move folder to destination
  copy:
    remote_src: true
    src: "{{ extract_folder.path }}/nextcloud/"
    dest: "{{ nextcloud_webroot }}"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 0755
  when:
    - not ansible_check_mode
    - not index.stat.exists
    - unarchive is succeeded
  tags:
    - nextcloud
    - install
    - tempfile
    - move

- name: delete temp folder
  file:
    path: "{{ extract_folder.path }}"
    state: absent
  when:
    - not ansible_check_mode
    - extract_folder.path is defined
  tags:
    - nextcloud
    - install
    - tempfile
