---
# tasks file for nextcloud
- import_tasks: dependencies.yml
- import_tasks: check-install.yml
- import_tasks: install.yml
- import_tasks: autoconfig.yml
- import_tasks: configure.yml
- import_tasks: cron.yml

- name: datadirectory
  file:
    path: "{{ nextcloud_datadirectory }}"
    state: directory
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 02770
  when:
    - nextcloud_datadirectory is defined
  tags:
    - nextcloud
    - datadirectory

- name: "config.php : datadirectory"
  lineinfile:
    path: '{{ nextcloud_webroot }}/config/config.php'
    regexp: 'datadirectory'
    line: "  'datadirectory' => '{{ nextcloud_datadirectory }}',"
    insertbefore: '^\);$'
    backup: true
  when:
    - config.stat.exists
    - nextcloud_datadirectory is defined
  tags:
    - nextcloud
    - config.php
    - datadirectory

- name: "config.php : trashbin"
  lineinfile:
    path: '{{ nextcloud_webroot }}/config/config.php'
    regexp: 'trashbin_retention_obligation'
    line:
      "  'trashbin_retention_obligation' =>
      '{{ nextcloud_trashbin_retention_obligation }}',"
    insertbefore: '^\);$'
    backup: true
  when:
    - config.stat.exists
    - nextcloud_trashbin_retention_obligation is defined
  tags:
    - nextcloud
    - config.php
    - trashbin

- name: "config.php : default_phone_region"
  lineinfile:
    path: '{{ nextcloud_webroot }}/config/config.php'
    regexp: 'default_phone_region'
    line: "  'default_phone_region' => '{{ nextcloud_default_phone_region }}',"
    insertbefore: '^\);$'
    backup: true
  when:
    - config.stat.exists
    - nextcloud_default_phone_region is defined
  tags:
    - nextcloud
    - config.php
    - phone_region
