---
# tasks file for nextcloud
- import_tasks: dependencies.yml
  tags:
    - nextcloud

- import_tasks: check-install.yml
  tags:
    - nextcloud

- import_tasks: install.yml
  when:
    - nextcloud_installed is undefined or not nextcloud_installed
  tags:
    - nextcloud

- name: datadirectory
  file:
    path: "{{ nextcloud_datadirectory }}"
    state: directory
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 02770
  when:
    - nextcloud_datadirectory is defined
  tags:
    - nextcloud
    - datadirectory

- import_tasks: configure.yml
  tags:
    - nextcloud

- name: maintenance:install
  ansible.builtin.command:
    chdir: "{{ nextcloud_webroot }}"
    cmd:
      runuser -u {{ nextcloud_user }} -- php{{ php_version }} occ
      maintenance:install
      --database "{{ nextcloud_config.dbtype }}"
      --database-name "{{ nextcloud_config.dbname }}"
      --database-host "{{ nextcloud_config.dbhost }}"
      --database-user "{{ nextcloud_config.dbuser }}"
      --database-pass "{{ nextcloud_config.dbpassword }}"
      --admin-user "{{ nextcloud_config.admin_username }}"
      --admin-pass "{{ nextcloud_config.admin_password }}"
      --data-dir "{{ nextcloud_config.datadir }}"
  when:
    - nextcloud_config is defined
    - nextcloud_installed is undefined or not nextcloud_installed
  tags:
    - nextcloud
    - maintenance
    - install

- import_tasks: cron.yml
  tags:
    - nextcloud
