---
# tasks file for nextcloud
- name: dependencies
  import_tasks: dependencies.yml
  tags:
    - nextcloud

- name: check install status
  import_tasks: check-install.yml
  tags:
    - nextcloud

- name: install
  import_tasks: install.yml
  when:
    - nextcloud_installed is undefined or not nextcloud_installed
  tags:
    - nextcloud

- name: datadirectory
  file:
    path: "{{ nextcloud_datadirectory }}"
    state: directory
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 02770
  when:
    - nextcloud_datadirectory is defined
  tags:
    - nextcloud
    - datadirectory

- name: instance specific config.php
  template:
    src: instance.config.php.j2
    dest: "{{ nextcloud_webroot }}/config/{{ nextcloud_instance }}.config.php"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 0644
  tags:
    - nextcloud
    - config

- name: maintenance:install
  ansible.builtin.command:
    chdir: "{{ nextcloud_webroot }}"
    cmd:
      runuser -u {{ nextcloud_user }} -- php{{ php_version | default(omit) }}
      occ maintenance:install
      --admin-user "{{ nextcloud_autoconfig.admin_username }}"
      --admin-pass "{{ nextcloud_autoconfig.admin_password }}"
      --data-dir "{{ nextcloud_autoconfig.datadir }}"
      --database "{{ nextcloud_autoconfig.dbtype }}"
      --database-host "{{ nextcloud_autoconfig.dbhost }}"
      --database-name "{{ nextcloud_autoconfig.dbname }}"
      --database-pass "{{ nextcloud_autoconfig.dbpassword }}"
      --database-user "{{ nextcloud_autoconfig.dbuser }}"
  when:
    - nextcloud_autoconfig is defined
    - nextcloud_installed is undefined or not nextcloud_installed
  changed_when: false
  tags:
    - nextcloud
    - maintenance
    - install

- name: cron
  cron:
    name: "{{ nextcloud_instance }}"
    minute: "*/{{ nextcloud_cron_frequency_min | default('5') }}"
    job: "php{{ php_version | default(omit) }}
        -f {{ nextcloud_webroot }}/cron.php"
    user: "{{ nextcloud_user }}"
    disabled: "{{ nextcloud_cron_disabled | default('false') }}"
  tags:
    - nextcloud
    - cron
