---
# tasks file for nextcloud
- import_tasks: dependencies.yml
  tags:
    - nextcloud

- import_tasks: check-install.yml
  tags:
    - nextcloud

- import_tasks: install.yml
  when:
    - nextcloud_installed is undefined or not nextcloud_installed
  tags:
    - nextcloud

- name: datadirectory
  file:
    path: "{{ nextcloud_datadirectory }}"
    state: directory
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 02770
  when:
    - nextcloud_datadirectory is defined
  tags:
    - nextcloud
    - datadirectory

- name: instance specific config.php
  template:
    src: instance.config.php.j2
    dest: "{{ nextcloud_webroot }}/config/{{ nextcloud_instance }}.config.php"
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_group }}"
    mode: 0644
  tags:
    - nextcloud
    - config

- name: maintenance:install
  ansible.builtin.command:
    chdir: "{{ nextcloud_webroot }}"
    cmd:
      runuser -u {{ nextcloud_user }} -- php{{ php_version }} occ
      maintenance:install
      --admin-user "{{ nextcloud_config.admin_username }}"
      --admin-pass "{{ nextcloud_config.admin_password }}"
      --data-dir "{{ nextcloud_config.datadir }}"
      --database "{{ nextcloud_config.dbtype }}"
      --database-host "{{ nextcloud_config.dbhost }}"
      --database-name "{{ nextcloud_config.dbname }}"
      --database-pass "{{ nextcloud_config.dbpassword }}"
      --database-user "{{ nextcloud_config.dbuser }}"
  when:
    - nextcloud_config is defined
    - nextcloud_installed is undefined or not nextcloud_installed
  tags:
    - nextcloud
    - maintenance
    - install

- name: cron
  cron:
    name: "{{ nextcloud_instance }}"
    minute: "*/{{ nextcloud_cron_frequency_min | default('5') }}"
    job: "php{{ php_version |
      default(__php_version) }} -f {{ nextcloud_webroot }}/cron.php"
    user: "{{ nextcloud_user }}"
  tags:
    - nextcloud
    - cron
