---
# handlers file for nextcloud
- name: nginx reload
  service:
    name: nginx
    state: reloaded

- name: php-fpm restart
  service:
    name: 'php{{ php_version }}-fpm'
    state: restarted
...
